[package]
name = "deve-sub-security"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
deve-sub-kernel = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
