[package]
name = "deve-sub-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
deve-sub-kernel = { workspace = true }
deve-sub-domain = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
percent-encoding = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
base64 = { workspace = true }
time = { workspace = true }
serde_yaml = { workspace = true }

[dev-dependencies]
deve-sub-emitter = { workspace = true }
deve-sub-compatibility = { workspace = true }
proptest = { workspace = true }
criterion = { workspace = true }

[[bench]]
name = "parse_10k"
harness = false

[lints]
workspace = true
