[package]
name = "deve-sub-application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
deve-sub-contract = { workspace = true }
deve-sub-domain = { workspace = true }
deve-sub-security = { workspace = true }
deve-sub-kernel = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
subtle = { workspace = true }

[lints]
workspace = true
