[package]
name = "deve-sub-adapters"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
deve-sub-application = { workspace = true }
deve-sub-domain = { workspace = true }
deve-sub-kernel = { workspace = true }
deve-sub-security = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
maxminddb = { workspace = true }
quinn = { workspace = true }
rustls = { workspace = true }
tokio-rustls = { workspace = true }
webpki-roots = { workspace = true }
sha2 = { workspace = true }
shadowsocks = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
async-trait = { workspace = true }
rcgen = { workspace = true }
flate2 = "1"
brotli = "7"
zstd = "0.13"

[lints]
workspace = true
